#!/usr/bin/env bash

# Displays "Best School" 10 times using while loop.

# On 9th iteration, display "Hi" instead of "Best school".

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
